### ISSUE TITLE
Nejdriv kontrolovat az potom transformovat?

### ISSUE THREAD

**Issue by fan1x** [kszabova/Tetris#1]
https://github.com/kszabova/Tetris/blob/f37d2d38dcba0a0f60130a9832b35a0a7c8159a2/Assets/Scripts/Tetramino.cs#L26

Neslo by to delat obracene? Nejdrive zkontrolovat, jestli je mozne transformovat a az potom to provest?

**Comment by kszabova** [comment]
Funkcia `IsValidPosition()` nema ziadne parametre, ale kontroluje poziciu daneho tetramina, takze v tomto pripade sa to musi najskor transformovat a potom skontrolovat. Urcite by sa to dalo najskor skontrolovat, keby `IsValidPosition()` napriklad mala parameter nejake tetramino.

**Comment by fan1x** [comment]
Jasné, já chtěl upozornit na to, že je lepší (ve většině případů) nejprve kontrolovat, jestli se akce může provést a až potom ji případně provést. Pokud by se jednalo o dlouhotrvající operaci, tak tenhle přístup by měl být lepší.
