### ISSUE TITLE
Jak tahle radka funguje?

### ISSUE THREAD

**Issue by fan1x** [kszabova/Tetris#2]
https://github.com/kszabova/Tetris/blob/f37d2d38dcba0a0f60130a9832b35a0a7c8159a2/Assets/Scripts/Game.cs#L157

Je potreba prirazovat do promenne, kdyz se ta hodnota nikdy nepouzije? Jak to, ze to funguje :)

**Comment by kszabova** [comment]
`(GameObject)Instantiate(...` samostatne sa neskompiluje kvoli chybe "Only assignment, call, increment, decrement, and new object expressions can be used as a statement". Teda je potrebne priradit to do nejakej premennej, aj ked sa nepouzije, inak by to pre C# nebol validny prikaz.

**Comment by fan1x** [comment]
A co dělá tedy přesně ta funkce `Instatiate()`? 

On není problém v tom, že by funkce musela být do něčeho přiřazena - nemusí, problém je, že návratová hodnota se přetypovává `(GameObject)`, což musí být použito pouze ve výrazu - tedy v tomhle případě přiřazeno
Takže pokud se vyhodí nepoužívé přetypování, tak už to funguje - `Instantiate(Resources.Load(GetRandomTetramino(), typeof(GameObject)), new Vector2(5, 20), Quaternion.identity);`

**Comment by kszabova** [comment]
Jasne, neuvedomila som si ze to pojde aj bez pretypovania, uz je to opravene

**Comment by fan1x** [comment]
> A co dělá tedy přesně ta funkce `Instatiate()`

?

**Comment by kszabova** [comment]
Vytvori kopiu objektu, ktory je uvedeny ako prvy argument, teda v tomto pripade nahodne tetramino ulozene v Resources, a umiestni ho na poziciu, co je druhy argument, s rotaciou, ktora je treti argument.
